-- PostgreSQL 版本 - 删除表结构

DROP TABLE IF EXISTS user_roles CASCADE;
DROP TABLE IF EXISTS user_operation_log CASCADE;
DROP TABLE IF EXISTS user_login_log CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS sys_menus CASCADE;
DROP TABLE IF EXISTS role_menus CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS dict_types CASCADE;
DROP TABLE IF EXISTS dict_data CASCADE;
DROP TABLE IF EXISTS casbin_rule CASCADE;
DROP TABLE IF EXISTS attachment CASCADE;