// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	captcha2 "github.com/wxlbd/gin-casbin-admin/internal/application/captcha"
	"github.com/wxlbd/gin-casbin-admin/internal/application/dict"
	"github.com/wxlbd/gin-casbin-admin/internal/application/menu"
	"github.com/wxlbd/gin-casbin-admin/internal/application/role"
	"github.com/wxlbd/gin-casbin-admin/internal/application/user"
	"github.com/wxlbd/gin-casbin-admin/internal/infrastructure/captcha"
	"github.com/wxlbd/gin-casbin-admin/internal/infrastructure/persistence"
	"github.com/wxlbd/gin-casbin-admin/internal/interfaces/api/v1"
	"github.com/wxlbd/gin-casbin-admin/internal/server"
	"github.com/wxlbd/gin-casbin-admin/pkg/casbinx"
	"github.com/wxlbd/gin-casbin-admin/pkg/config"
	"github.com/wxlbd/gin-casbin-admin/pkg/gormx"
	"github.com/wxlbd/gin-casbin-admin/pkg/jwtx"
	"github.com/wxlbd/gin-casbin-admin/pkg/log"
	"github.com/wxlbd/gin-casbin-admin/pkg/redisx"
)

// Injectors from wire.go:

func NewWire(cfg *config.Config, logger *log.Logger) (*gin.Engine, func(), error) {
	client, err := redisx.New(cfg)
	if err != nil {
		return nil, nil, err
	}
	jwt := jwtx.New(cfg, client)
	db := gormx.NewDB(cfg, logger)
	repository := persistence.NewUserRepository(db)
	service := user.NewUserService(logger, repository, jwt)
	userHandler := v1.NewUserHandler(service, cfg)
	roleRepository := persistence.NewRoleRepository(db)
	menuRepository := persistence.NewMenuRepository(db)
	enforcer, err := casbinx.New(db)
	if err != nil {
		return nil, nil, err
	}
	roleService := role.NewRoleService(roleRepository, menuRepository, enforcer)
	roleHandler := v1.NewRoleHandler(roleService)
	menuService := menu.NewMenuService(menuRepository)
	menuHandler := v1.NewMenuHandler(menuService)
	dictRepository := persistence.NewDictRepository(db)
	dictService := dict.NewDictService(dictRepository)
	dictHandler := v1.NewDictHandler(dictService)
	redisStore := captcha.NewRedisStore(client)
	captchaService := captcha2.NewCaptchaService(redisStore)
	captchaHandler := v1.NewCaptchaHandler(captchaService)
	engine := server.NewServerHTTP(cfg, logger, jwt, userHandler, roleHandler, menuHandler, dictHandler, captchaHandler, enforcer, service)
	return engine, func() {
	}, nil
}

// wire.go:

var ServerSet = wire.NewSet(server.NewServerHTTP)

var UserSet = wire.NewSet(persistence.NewUserRepository, user.NewUserService, v1.NewUserHandler)

var RoleSet = wire.NewSet(persistence.NewRoleRepository, role.NewRoleService, v1.NewRoleHandler)

var MenuSet = wire.NewSet(persistence.NewMenuRepository, menu.NewMenuService, v1.NewMenuHandler)

var DictSet = wire.NewSet(persistence.NewDictRepository, dict.NewDictService, v1.NewDictHandler)

var CaptchaSet = wire.NewSet(captcha.NewRedisStore, captcha2.NewCaptchaService, v1.NewCaptchaHandler)
